# fly deploy fly/apps/scylladb
app = "scylla-dna-demo"
primary_region = "nrt"


[deploy]
  strategy = "immediate"

[env]
  MEMORY_LIMIT = "200M"

# fly volumes create scylla_data --no-encryption --region nrt --size 1 --app scylla-dna-demo
[[mounts]]
  source = "scylla_data"
  destination = "/var/lib/scylla"
