# fly deploy -c fly/apps/dna-demo/fly.toml
app = "dna-demo"
primary_region = "nrt"

# see fly/apps/scylladb first
# flyctl secrets set SECRET_KEY_BASE=xxxxxxxx  # from mix phx.gen.secret
[env]
  KNOWN_NODES = "nrt.scylla-dna-demo.internal:9042"
  PHX_SERVER = "true"
  PHX_HOST = "dna-demo.fly.dev"

[build]
  dockerfile = "./../../../Dockerfile"

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false